[phases.setup]
nixPkgs = ['nodejs_18', 'npm']

[phases.install]
cmds = ['npm install']

[phases.build]
cmds = ['echo "Build complete"']

[start]
cmd = 'npx sequelize-cli db:migrate && node src/app.js'
